apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-blue-deployment
  namespace: jdh
  labels:
    type: backend
    slot: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      slot: blue
  template:
    metadata:
      labels:
        type: backend
        slot: blue
    spec:
      containers:
        - name: backend
          image: deatytim/tmbackend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
