server {
    listen 80;
    server_name www.tallemalletest.kro.kr;

    root /usr/share/nginx/html;
    index index.html;

    # Vue Router (History mode) 지원
    location / {
        try_files $uri $uri/ /index.html;
    }
}
